version: "2"
services:
  node:
    image: myungji/orchestrive:test
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - mysql
    restart: always
    depends_on:
      - mysql
    networks:
      - db-net
  mysql:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13306:13306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 13306
      MYSQL_DATABASE: orchestrive
    expose:
      - "13306"
    networks:
      - db-net 
networks:
  db-net: